import { sr_RS } from "ng-zorro-antd/i18n";

export const API = {
    AUTH: {
        LOGIN: '/hms/login/user-login',
        PROFILE: `/hms/login/profile`,
        FORGOT_PASSWORD: '/hms/login/forgot-password',
        CHANGE_PASSWORD: '/hms/login/change-password',
        REFRESH: '/hms/login/refresh',
        LOGOUT: `/hms/login/logout`,

    },

    MODULES: {
        GET_ALL: '/user/modules',
    },
    JOBS: {
        GET_ALL_JOBS: `/hms/create-job/get-all-jobs`,
        GET_DASHBOARD_DATA: "/hms/jobs/get-all-jobs-dashboard-counts",
        GET_JOB_BY_ID: (id: any) => `/hms/create-job/get-job-details/${id}`
        , ADD_JOB: `/hms/jobs/add-new-job`,
        UPDATE_JOB: `/hms/jobs/update-job-details`,
        GET_ALL_SKILLS: `/hms/jobs/get-all-skills`,
        GET_ACTIVITY_LOGS: `/hms/job-overview/activity-feed`,
        // ADD_APPLICANT: `/job/application`,
        ADD_APPLICANT:`/hms/jobs/application`,
        GET_JOBS_BY_COUNTRY: (country: any) => `/job/get-all-jobs-by-country?jobCountry=${country}`,
        //    GET_JOB_BY_ID:(id:any)=>`/jobs/get-job-details-by-id/${id}`,
        GET_ALL_APPLICANTS: () => `/hms/jobs/get-all-jobs-applicant`,
        GET_CANDIDATE_BY_ID: () => `/hms/jobs/get-candidate-by-id`,
        GET_APPLICANT_BY_ID: (id: any) => `/hms/jobs/view-applicant-by-id/${id}`,
        GET_APPLICANT_DETAILS_BY_ID: (id: any) => `/hms/jobs/get-applicant-details-by-id/${id}`,
        GET_ALL_ANALYSIS: '/api/resume/analysis',
        MOVE_TO_INTERVIEW: `/api/interview/create-interview-session`,
        UPDATE_APPLICANT_BY_ID: '/api/interview/update-final-candidate-decision',
        SCHEDULE_INTERVIEW: '/api/interview/admin-schedule-interview',
        DELETE_JOB: (id: any) => `/hms/jobs/delete-job-by-id/${id}`,
        VIEW_RESUME: (type: any, user: any, action: any) => `/job/download/${type}?appId=${user}&action=${action}`,
        ANALYSIS_RESUME: `/api/resume/analyze/batch`,
        INTERVIEW_ANALYSIS: `/api/interview/fetch-interview-analysis`,
        LOAD_ROLES:`/hms/configurations/roles/by-departments`,
        LOAD_RECRUITERS:`/hms/create-job/get-recruiters`,
        CREATE_JOB_BY_SR_ID : (id : any) => `/hms/create-job/details/${id}`,
        CREATE_NEW_JOB : '/hms/create-job/new-job',
        CREATE_ASSIGNED_USERS:(id:any)=>`/hms/recruiter/assigned-recruiters/${id}`,
        UPDATE_ASSIGN_USERS:`/hms/recruiter/assign-more-recruiters`,
        UPDATE_JOB_TO_CLOSE:`/hms/create-job/update-job-details-by-jobid`,
        AGENCY_LIST:`/hms/create-job/agency-list`,
        AGENCY_CATEGORIES:`/hms/configurations/categories`,
         REQUEST_FOR_REUPLOAD:(id:any)=>`/hms/candidate/raise-reupload-request/${id}`
    },
    USERS: {
        CREATE: '/hms/user/create',
        GET_LIST: `/hms/user/list`,
        COUNT: '/hms/user/count',
        COUNT_ROLE: (role: any) => `/hms/user/count/role/${role}`,
        COUNT_STATUS: (status: any) => `/hms/user/count/status?status=${status}`,
        USER_DETAILS_BY: (id: any) => `/hms/user/details/${id}`,
        UPDATE_BY_ID: (id: any) => `/hms/user/update/${id}`,
        BUSSINESS_UNITS: '/hms/configurations/business-units',
        DEPARTMENTS: (bussinessId: any) => `/hms/configurations/departments/${bussinessId}`,
        ROLES_BY_DEPT: (departmentId: any) => `/hms/configurations/roles/${departmentId}`,
        EMP_TYPES: `/hms/configurations/employment-types`,
        USER_TYPES: `/hms/configurations/user-types`,
        JOB_BY_EXPORT: (jobId: any) => `/api/report/generate-applicants-report/${jobId}`,
        EXPORT_BY_APPLICANT: (id: any) => `/api/report/generate-candidate-report/${id}`,
       
    },
    ROLES: {
        ADD_ROLE: `/hms/role/add-role`,
        UPDATE: `/hms/role/update-role-permissions`,
        GET_ALL_PERMISSIONS: `/hms/role/get-all-role-permissions`,
        GET_ALL_MODULES: `/hms/configurations/get-all-modules`,
        GET_ROLES_MATRIX: `/hms/role/get-role-permission-matrix`,
        USERS_BY_ROLE_ID: (id: any) => `/hms/role/usernames-by-roleid/${id}`,
        GET_PERMISSIONS_BY_ROLE: (id: any) => `/hms/role/get-permissions-by-role/${id}`
    },
    ROLE_AND_REQUIREMENTS: {
        MUST_HAVE_SKILLS: `/api/admin/ai-suggest-must-have-skills`,
        NICE_SKILLS: `/api/admin/ai-suggest-nice-to-have-skills`,
        EDUCATION_REQUIREMENTS: `/api/admin/qualifications-suggestions`,
        CERTIFICATE: `/api/admin/certifications-suggestions`,
        LANGUAGE: `/api/admin/language-suggestions`,
        QUALIFICATION: `/api/admin/qualifications-suggestions`,
        CTC: `/api/admin/ctc-review`
    },
    SRS: {
        STAFFING_CREATION: `/hms/staffing-requisition/new-staffing-requisition`,
        SENIORITY: `/hms/configurations/position-basic-seniority-levels`,
        TRAVEL: `/hms/configurations/travel-requirements`,
        ALL_SRS: `/hms/staffing-requisition/sr-list`,
        BY_SR_ID: `/hms/staffing-requisition/by-sr-id`,
        MY_SRS_COUNT:`/hms/staffing-requisition/get-all-sr-list-count`,
        REQUESTED_BY:`/hms/configurations/role-users`,
        APPROVED_SRS:`/hms/staffing-requisition/approved-srs`,
        SEARCH_JOB:(job:string)=>`/api/admin/job-titles/live-search?q=${job}`
    },
    SUPPLY: {
        KANBAN: `/hms/kanban/filter`,
        ASSIGNED_COUNT:`/hms/recruiter/my-job-assignments-count`,
        ASSIGNED_LIST:`/hms/recruiter/my-job-assignments`,
        ASSIGNED_JOB_BY_ID:(id:any)=>`/hms/create-job/get-job-details/${id}`,
        JOB_DECISION:`/hms/recruiter/update-recruiter-assignment`
    },
    APPROVALS: {
        CREATE_CHAIN: `/hms/approval-chains/create`,
        GET_FUNCTIONALITIES: `/hms/configurations/get-all-functionalities`,
        UPDATE_CHAIN: `/hms/approval-chains/update`,
        APPROVAL_CHAIN_COUNT: `/hms/approval-chains/count`,
        APPROVAL_CHAIN_DETAILS: (id: any) => `/hms/approval-chains/details/${id}`,
        APPROVAL_CHAIN_LIST: `/hms/approval-chains/list`,
        DEPATMENTS: `/hms/configurations/departments`,
        SR_DETAILS: (srId: string) => `/hms/staffing-requisition/approval-view/${srId}`,
        APPROVE_OR_REJECT: `/hms/staffing-requisition/sr-approval`,
    },
    NOTIFICATIONS: {
        ALL_NOTIFICATIONS: `/hms/notifications/list`,
        NOTIFICATION_COUNTS: `/hms/notifications/counts`,
        MARK_AS_READ: `/hms/notifications/update`,
    },
    SR_APPROVALS: {
        COUNT: `/hms/staffing-requisition/sr-counts`,
        LIST: `/hms/staffing-requisition/assigned-srs-for-approvals`,
        FUNCATNALITIES:    `/hms/configurations/functionality`,
    },
    RECRUITER_TRACKING:{
        RECRUITER_COUNT:`/hms/recruiter/counts`,
        LIST:`/hms/recruiter/job-assignment-list`,
        DETAILS_BY_ID:(id:any)=>`/hms/recruiter/job-assignment-details-list/${id}`,
        COUNT:(id:any)=>`/hms/recruiter/job-assignment-summary/${id}`
    },
    INTERVIEW:{
        CREATE_CONFIG:`/hms/interview-plan/create`,
        INTERVIEW_PLAN_COUNT:`/hms/interview-plan/counts`,
        INTERVIEW_PLAN_LIST:`/hms/interview-plan/list`,
        INTERVIEW_PLAN_LIST_FOR_APPROVAL:`/hms/interview-plan/interview-plan-approvals`,
        CREATED_BY_LIST:`/hms/configurations/create-permission-users`,
        PLAN_DETAILS_BY:(id:any)=>`/hms/interview-plan/interview-plan-details-by-id/${id}`,
        UPDATE_CONFIG:`/hms/interview-plan/update`,
        PLANS_LIST:`/hms/configurations/interview-plans`,
        INTERVIEW_ASSIGNED_LIST:`/hms/interviewer-assignment/list`,
        GET_INTERVIEW_ASSIGNMENT_DETAILS:(id:any)=>`/hms/interviewer-assignment/details/${id}`,
        INTERVIEW_UPDATE:`/hms/interviewer-assignment/assign`,
        INTERVIEW_ASSIGNMENT_COUNTS:`/hms/interviewer-assignment/counts`,
        GET_INTERVIEW_ASSIGNEMENT_BY_ID:(id:any)=>`/hms/interviewer-assignment/assign-interview-by-id/${id}`,
        GET_ASSIGN_INTERVIEW_LIST:`/hms/interviewer-assignment/get-all-assigned-interviews`,
        UPDATE_INTERVIEW_ASSIGN:`/hms/interviewer-assignment/update`,
        GET_JOB_DETAILS_BYID:(id:any)=>`/hms/create-job/get-job-details/${id}`,
        INTERVIEW_CANDIDATE_DETAILS:`/api/resume/analysis/update`,
        GET_AI_INTERVEW_ZONE_COUNTS:`/hms/ai-interview-zone/dashboard-counts`,
        GET_AI_INTERVEW_ZONE_JOBS:`/hms/configurations/jobs`,
        GET_AI_INTERVIEW_PLANS_LIST:`/hms/configurations/interview-plans`,
        GET_AI_INTERVEW_ZONE_LIST:`/hms/ai-interview-zone/list`,
        GET_AI_INTERVEW_SCHEDULE_INTERVIEW:`/hms/interview-plan/get-all-ai-interviews`,
        GET_UPCOMMING_LIST:`/hms/ai-interview-zone/get-all-interviews-in-progress`,
        CREATE_INTERVIEW_SESSION:`/api/interview/create-interview-session`,
        GENERATE_AI_QUESTIONS:`/api/interview/generate-ai-questions`,
        CUSTOM_QUESTION:`/api/interview/custom-question`,
        FINALIZE_QUESTIONS:`/api/interview/finalize-questions`,
        UPDATE_MOVE_TO_SCHEDULE:`/api/interview/move-to-schedule`,
        AI_INTERVIEW_DETAILS:(id:any)=>`/hms/interview-plan/interview-progress-details/${id}`,
        SCHEDULE_USER:`/api/interview/admin-schedule-interview`,
        SCHEDULE_CANDIDATE_OVERVIEW:(id:any)=>`/hms/interview-plan/candidate-overview/${id}`,
        INTERVIEW_PROVIDE_FEEDBACK:"/hms/interview-plan/interview-feedback",
        ROUNDS_LIST:'/hms/configurations/interview-rounds',
        SUBMIT_FEED_BACK:`/hms/interview-plan/interview-feedback`,
        TODAY_INTERVIEW_DETAILS:`/hms/interview-plan/today-interview-details`,
        GET_TODAY_INTERVIEW_LIST:`/hms/interview-plan/get-today-interviews`,
        GET_FEED_BACK_LIST:`/hms/interview-plan/feedback-list`,
        GET_SCHEDULE_LIST:`/hms/interview-plan/get-to-be-schedule-list`,
        LOAD_FINALISED_QUESTIONS:(id:any)=>`/api/interview/get-all-generate-ai-questions?application_id=${id}`,
        CANDIDATE_MANAGEMENT_LIST:`/hms/interview-plan/progress-list`,
        CANDIDATE_MANAGEMENT_LISt_COUNT:`/hms/interview-plan/progress-count`,
        GET_UPCOMMING_REQUEST_LIST:`/hms/interview-plan/interview-upcoming-list`,
        CANDIDATE_SUMMARY_DETAILS:(id:any)=>`/hms/interview-plan/interview-summary/${id}`,
        AI_INTERVIEW_FEED_BACK:`/api/interview/interview-feedback`,
        SCHEDULE_INTERVIEW_TO_CANDIDATE:`/hms/interview-plan/interview-schedule`,
        RESCHEDULE_INTERVIEW_FOR_CANDIDATE:`/hms/interview-plan/rescedule-interview`,
        SCHEDULE_INTERVIEW_DETAILS_FOR_CANDIDATE:(id:any)=>`/hms/interview-plan/get-interview-schedule-details-by-id/${id}`,
        AI_EVALUATION_SUMMARY:(id:any)=>`/api/interview/evaluation-summary?application_id=${id}`,
        CALCULATE_EVALUATION_SUMMARY:`/api/interview/calculate-evaluation-summary`,
        UPDATE_INTERVIEW_COMPLETE:`/hms/interview-plan/update-interview-completion-status`,
        INTERVIEW_COMPLETE_TO_CANDIDATE:`/hms/interview-plan/interview-complete`,
        INTERVIEW_ASSIGNMENTS_COUNT:`/hms/interviewer-assignment/interviewers-assignment-counts`,
        INTERVIEW_FEED_BACK_BY_ID:`/hms/interview-plan/applicant-feedback-by-id`,
        UPDATE_INTERVIEW_FEED_BACK:`/hms/interview-plan/update-interview-feedback`
    },
    CANDIDATE_MANANGEMENT:{
        RELEASE_OFFER:`/hms/offer-details/release-offers`,
        READY_TO_RELEASE_OFFER_LIST:`/hms/offer-details/ready-to-release-list`,
        RAISE_REQUEST_LIST:`/hms/offer-details/get-all-raise-offer-requests`,
        CARDS_COUNT:`/hms/offer-details/dashboard-counts`,
        OFFER_DETAILS_BY_APPLICANT_ID:(id:any)=>`/hms/offer-details/get-offer-details-by-applicant-id/${id}`,
        COMMENTS_FOR_OFFER_ID:(id:any)=>`/hms/offer-details/get-offer-comments/${id}`,
        OFFER_APPROVE:`/hms/offer-details/approve-offer`,
        GET_PENDING_APPROVALS:`/hms/offer-details/get-pending-approvals`,
        GET_OFFER_TEMPLATED:`/hms/configurations/offer-letter-templates`,
        SUBMIT_RISE_OFFER_REQUEST:`/hms/offer-details/submit-raise-offer-request`,
        GENERATE_OFFER_LETTER:`/api/admin/generate-offer-letter`,
        VIEW_OFFER_LETTER:(id:any)=>`/hms/offer-details/download/offerLetter?appId=${id}&action=view`,
        OPPROVE_OFFER_LIST:`/hms/offer-details/get-all-pending-approvals`,
        GET_NAGOTIATE_LIST:`/hms/offer-details/negotiation-list`,
        DEPARMENT:`/hms/configurations/get-departments`,
        GET_CANDIDATE_RESPONSE:`/hms/offer-details/candidate-response`,
        OFFER_APPROVALS_LIST:`/hms/offer-details/get-pending-approvals`,
        NEGOTIATION_DETAILS_BY_APPLICANT_ID:(id:any)=>`/hms/offer-details/negotiation-details/${id}`,
        REVIEW_NEGOTIATION_REQUEST:`/hms/offer-details/review-negotiation-request`,
        VIEW_DOCUMENTS:`/hms/offer-details/view-document`,
        RERELEASE_OFFER_DETAILS:(id:any)=>`/hms/offer-details/re-release-offer-details-by-id/${id}`,
    },
    DASHBOARD:{
        HIRING_MANAGER_COUNT:`/hms/dashboard/hiring`,
        
        RECRUITER_DASHBOARD_COUNT:`/hms/dashboard/recruiter`,
        RECRUITER_DASHBOARD:`/hms/dashboard/analytics`,
        
        HIRING_MANAGER_DASHBOARD:`/hms/dashboard/hiring-dashboard-analytics`,

    }
};