import { Routes } from '@angular/router';

export const INTERVIEW_ROUTES: Routes = [
    {
        path: 'interview-plan',
        loadComponent:()=>import("../components/interview-plans/interview-plans.component").then(m=>m.InterviewPlansComponent)
    },
    {
        path:"interview-approval-plans",
        loadComponent:()=>import("../components/interview-plain-aproval/interview-plain-aproval.component").then(m=>m.InterviewPlainAprovalComponent)
    },
    {
        path:"interview-plan/create",
        loadComponent:()=>import("../components/interview-plan-create/interview-plan-create.component").then(m=>m.InterviewPlanCreateComponent)
    },
    {
        path:"interview-plan/view/:id",
        loadComponent:()=>import("../components/interview-plan-view/interview-plan-view.component").then(m=>m.InterviewPlanViewComponent)
    },
    {
        path:"interview-approval-plans/review-and-approve/:id",
        loadComponent:()=>import("../components/approve-interview-plan/approve-interview-plan.component").then(m=>m.ApproveInterviewPlanComponent)
    },
    {
        path:"ai-interview-zone",
        loadComponent:()=>import("../components/ai-interview-zone/ai-interview-zone.component").then(m=>m.AiInterviewZoneComponent)
    },
    {
        path:"assign-interviewers",
        loadComponent:()=>import("../components/assign-interviewers/assign-interviewers.component").then(m=>m.AssignInterviewersComponent)
    },
    {
        path:"assign-interviewers/new-assign",
        loadComponent:()=>import("../components/assign-interviewers-by-list/assign-interviewers-by-list.component").then(m=>m.AssignInterviewersByListComponent)
    },
    {
        path:"assign-interviewers/view",
        loadComponent:()=>import("../components/view-assign-recruter-response/view-assign-recruter-response.component").then(m=>m.ViewAssignRecruterResponseComponent)
    },
    {
        path:"assigend-interview-requests",
        loadComponent:()=>import("../components/assigned-interview-requests/assigned-interview-requests.component").then(m=>m.AssignedInterviewRequestsComponent)
    },
    {
        path:"assigend-interview-requests/response/:id",
        loadComponent:()=>import("../components/interview-assignment-response/interview-assignment-response.component").then(m=>m.InterviewAssignmentResponseComponent)
    },
    {
        path:"assigend-interview-requests/reschedule-interview",
        loadComponent:()=>import("../components/reschedule-interview/reschedule-interview.component").then(m=>m.RescheduleInterviewComponent)
    },
    {
        path:"assigend-interview-requests/schedule-interview",
        loadComponent:()=>import("../components/schedule-interview/schedule-interview.component").then(m=>m.ScheduleInterviewComponent)
    },
    {
        path:"assigend-interview-requests/provide-feedback",
        loadComponent:()=>import("../components/provide-feed-back/provide-feed-back.component").then(m=>m.ProvideFeedBackComponent)
    },

]